package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.ItoUserProfile;
import com.bruce.geekway.model.ItoUserProfileCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItoUserProfileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    int countByExample(ItoUserProfileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    int deleteByExample(ItoUserProfileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    int insert(ItoUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    int insertSelective(ItoUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    List<ItoUserProfile> selectByExample(ItoUserProfileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    ItoUserProfile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    int updateByExampleSelective(@Param("record") ItoUserProfile record, @Param("example") ItoUserProfileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    int updateByExample(@Param("record") ItoUserProfile record, @Param("example") ItoUserProfileCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    int updateByPrimaryKeySelective(ItoUserProfile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ito_user_profile
     *
     * @mbggenerated Tue Jun 17 09:40:03 CST 2014
     */
    int updateByPrimaryKey(ItoUserProfile record);
}