package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.KlhUserScoreHistory;
import com.bruce.geekway.model.KlhUserScoreHistoryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KlhUserScoreHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    int countByExample(KlhUserScoreHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    int deleteByExample(KlhUserScoreHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    int insert(KlhUserScoreHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    int insertSelective(KlhUserScoreHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    List<KlhUserScoreHistory> selectByExample(KlhUserScoreHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    KlhUserScoreHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    int updateByExampleSelective(@Param("record") KlhUserScoreHistory record, @Param("example") KlhUserScoreHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    int updateByExample(@Param("record") KlhUserScoreHistory record, @Param("example") KlhUserScoreHistoryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    int updateByPrimaryKeySelective(KlhUserScoreHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_user_score_history
     *
     * @mbggenerated Sun Jun 01 09:38:02 CST 2014
     */
    int updateByPrimaryKey(KlhUserScoreHistory record);
}