package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.KlhVoteResult;
import com.bruce.geekway.model.KlhVoteResultCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface KlhVoteResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    int countByExample(KlhVoteResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    int deleteByExample(KlhVoteResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    int insert(KlhVoteResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    int insertSelective(KlhVoteResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    List<KlhVoteResult> selectByExample(KlhVoteResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    KlhVoteResult selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    int updateByExampleSelective(@Param("record") KlhVoteResult record, @Param("example") KlhVoteResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    int updateByExample(@Param("record") KlhVoteResult record, @Param("example") KlhVoteResultCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    int updateByPrimaryKeySelective(KlhVoteResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table klh_vote_result
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    int updateByPrimaryKey(KlhVoteResult record);
}