package com.bruce.geekway.dao.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.bruce.geekway.model.KlhWallImageLog;
import com.bruce.geekway.model.KlhWallImageLogCriteria;
import com.bruce.geekway.model.KlhWallImageStatBean;

public interface KlhWallImageLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	int countByExample(KlhWallImageLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	int deleteByExample(KlhWallImageLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	int insert(KlhWallImageLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	int insertSelective(KlhWallImageLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	List<KlhWallImageLog> selectByExample(KlhWallImageLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	KlhWallImageLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	int updateByExampleSelective(@Param("record") KlhWallImageLog record, @Param("example") KlhWallImageLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	int updateByExample(@Param("record") KlhWallImageLog record, @Param("example") KlhWallImageLogCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	int updateByPrimaryKeySelective(KlhWallImageLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_wall_image_log
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	int updateByPrimaryKey(KlhWallImageLog record);
	
	
	List<KlhWallImageStatBean> weeklyStat();
	
	List<KlhWallImageStatBean> monthlyStat();
	
	List<KlhWallImageStatBean> totalStat();
	
}