package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.ProductTagRelation;
import com.bruce.geekway.model.ProductTagRelationCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductTagRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	int countByExample(ProductTagRelationCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	int deleteByExample(ProductTagRelationCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	int insert(ProductTagRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	int insertSelective(ProductTagRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	List<ProductTagRelation> selectByExample(
			ProductTagRelationCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	ProductTagRelation selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	int updateByExampleSelective(@Param("record") ProductTagRelation record,
			@Param("example") ProductTagRelationCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	int updateByExample(@Param("record") ProductTagRelation record,
			@Param("example") ProductTagRelationCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	int updateByPrimaryKeySelective(ProductTagRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_product_tag_relation
	 * @mbggenerated  Thu Nov 06 11:52:06 CST 2014
	 */
	int updateByPrimaryKey(ProductTagRelation record);
}