package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.ProductTag;
import com.bruce.geekway.model.ProductTagCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProductTagMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	int countByExample(ProductTagCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	int deleteByExample(ProductTagCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	int insert(ProductTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	int insertSelective(ProductTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	List<ProductTag> selectByExample(ProductTagCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	ProductTag selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	int updateByExampleSelective(@Param("record") ProductTag record,
			@Param("example") ProductTagCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	int updateByExample(@Param("record") ProductTag record,
			@Param("example") ProductTagCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	int updateByPrimaryKeySelective(ProductTag record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table tb_product_tag
	 * @mbggenerated  Tue Jan 13 17:37:49 CST 2015
	 */
	int updateByPrimaryKey(ProductTag record);
}