package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.SkuPropValue;
import com.bruce.geekway.model.SkuPropValueCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SkuPropValueMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	int countByExample(SkuPropValueCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	int deleteByExample(SkuPropValueCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	int insert(SkuPropValue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	int insertSelective(SkuPropValue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	List<SkuPropValue> selectByExample(SkuPropValueCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	SkuPropValue selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	int updateByExampleSelective(@Param("record") SkuPropValue record,
			@Param("example") SkuPropValueCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	int updateByExample(@Param("record") SkuPropValue record,
			@Param("example") SkuPropValueCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	int updateByPrimaryKeySelective(SkuPropValue record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_sku_prop_value
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	int updateByPrimaryKey(SkuPropValue record);
}