package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.WxAccessToken;
import com.bruce.geekway.model.WxAccessTokenCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxAccessTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    int countByExample(WxAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    int deleteByExample(WxAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    int insert(WxAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    int insertSelective(WxAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    List<WxAccessToken> selectByExample(WxAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    WxAccessToken selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    int updateByExampleSelective(@Param("record") WxAccessToken record, @Param("example") WxAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    int updateByExample(@Param("record") WxAccessToken record, @Param("example") WxAccessTokenCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    int updateByPrimaryKeySelective(WxAccessToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_access_token
     *
     * @mbggenerated Tue Aug 12 13:08:57 CST 2014
     */
    int updateByPrimaryKey(WxAccessToken record);
}