package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.WxAppJsapiRelation;
import com.bruce.geekway.model.WxAppJsapiRelationCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxAppJsapiRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	int countByExample(WxAppJsapiRelationCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	int deleteByExample(WxAppJsapiRelationCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	int insert(WxAppJsapiRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	int insertSelective(WxAppJsapiRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	List<WxAppJsapiRelation> selectByExample(WxAppJsapiRelationCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	WxAppJsapiRelation selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	int updateByExampleSelective(@Param("record") WxAppJsapiRelation record,
			@Param("example") WxAppJsapiRelationCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	int updateByExample(@Param("record") WxAppJsapiRelation record,
			@Param("example") WxAppJsapiRelationCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	int updateByPrimaryKeySelective(WxAppJsapiRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_app_jsapi_relation
	 * @mbggenerated  Mon Jan 26 16:54:13 CST 2015
	 */
	int updateByPrimaryKey(WxAppJsapiRelation record);
}