package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.WxDefaultReply;
import com.bruce.geekway.model.WxDefaultReplyCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxDefaultReplyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	int countByExample(WxDefaultReplyCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	int deleteByExample(WxDefaultReplyCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	int insert(WxDefaultReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	int insertSelective(WxDefaultReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	List<WxDefaultReply> selectByExample(WxDefaultReplyCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	WxDefaultReply selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	int updateByExampleSelective(@Param("record") WxDefaultReply record,
			@Param("example") WxDefaultReplyCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	int updateByExample(@Param("record") WxDefaultReply record,
			@Param("example") WxDefaultReplyCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	int updateByPrimaryKeySelective(WxDefaultReply record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_default_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	int updateByPrimaryKey(WxDefaultReply record);
}