package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.WxMaterial;
import com.bruce.geekway.model.WxMaterialCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxMaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    int countByExample(WxMaterialCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    int deleteByExample(WxMaterialCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    int insert(WxMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    int insertSelective(WxMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    List<WxMaterial> selectByExample(WxMaterialCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    WxMaterial selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    int updateByExampleSelective(@Param("record") WxMaterial record, @Param("example") WxMaterialCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    int updateByExample(@Param("record") WxMaterial record, @Param("example") WxMaterialCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    int updateByPrimaryKeySelective(WxMaterial record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_material
     *
     * @mbggenerated Tue May 06 15:15:28 CST 2014
     */
    int updateByPrimaryKey(WxMaterial record);
    
    
    
    /**
     * 根据查询commandId相关的文章
     * @param commandId
     * @return
     */
    List<WxMaterial> queryMaterialsByCommandId(@Param("commandId")int commandId);
    
    /**
     * 根据查询commandId相关的文章
     * @param commandId
     * @return
     */
    List<WxMaterial> queryMaterialsByCommandIdLimit(@Param("commandId")int commandId, @Param("limit")int limit);
    
    /**
     * 根据查询commandId不相关的文章
     * @param commandId
     * @return
     */
    List<WxMaterial> queryMaterialsOutCommandId(int commandId);
}