package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.WxPayNotifyOrder;
import com.bruce.geekway.model.WxPayNotifyOrderCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxPayNotifyOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    int countByExample(WxPayNotifyOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    int deleteByExample(WxPayNotifyOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    int insert(WxPayNotifyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    int insertSelective(WxPayNotifyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    List<WxPayNotifyOrder> selectByExample(WxPayNotifyOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    WxPayNotifyOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    int updateByExampleSelective(@Param("record") WxPayNotifyOrder record, @Param("example") WxPayNotifyOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    int updateByExample(@Param("record") WxPayNotifyOrder record, @Param("example") WxPayNotifyOrderCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    int updateByPrimaryKeySelective(WxPayNotifyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_pay_notify_order
     *
     * @mbggenerated Tue Sep 23 18:09:55 CST 2014
     */
    int updateByPrimaryKey(WxPayNotifyOrder record);
}