package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.WxSkuPropValue;
import com.bruce.geekway.model.WxSkuPropValueCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxSkuPropValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    int countByExample(WxSkuPropValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    int deleteByExample(WxSkuPropValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    int insert(WxSkuPropValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    int insertSelective(WxSkuPropValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    List<WxSkuPropValue> selectByExample(WxSkuPropValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    WxSkuPropValue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    int updateByExampleSelective(@Param("record") WxSkuPropValue record, @Param("example") WxSkuPropValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    int updateByExample(@Param("record") WxSkuPropValue record, @Param("example") WxSkuPropValueCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    int updateByPrimaryKeySelective(WxSkuPropValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_sku_prop_value
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    int updateByPrimaryKey(WxSkuPropValue record);
}