package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.WxUserAddress;
import com.bruce.geekway.model.WxUserAddressCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxUserAddressMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	int countByExample(WxUserAddressCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	int deleteByExample(WxUserAddressCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	int insert(WxUserAddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	int insertSelective(WxUserAddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	List<WxUserAddress> selectByExample(WxUserAddressCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	WxUserAddress selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	int updateByExampleSelective(@Param("record") WxUserAddress record,
			@Param("example") WxUserAddressCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	int updateByExample(@Param("record") WxUserAddress record,
			@Param("example") WxUserAddressCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	int updateByPrimaryKeySelective(WxUserAddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_user_address
	 * @mbggenerated  Thu Oct 16 13:09:20 CST 2014
	 */
	int updateByPrimaryKey(WxUserAddress record);
}