package com.bruce.geekway.dao.mapper;

import com.bruce.geekway.model.WxWebUser;
import com.bruce.geekway.model.WxWebUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WxWebUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	int countByExample(WxWebUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	int deleteByExample(WxWebUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	int insert(WxWebUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	int insertSelective(WxWebUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	List<WxWebUser> selectByExample(WxWebUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	WxWebUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	int updateByExampleSelective(@Param("record") WxWebUser record,
			@Param("example") WxWebUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	int updateByExample(@Param("record") WxWebUser record,
			@Param("example") WxWebUserCriteria example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	int updateByPrimaryKeySelective(WxWebUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table wx_web_user
	 * @mbggenerated  Fri Nov 28 14:22:47 CST 2014
	 */
	int updateByPrimaryKey(WxWebUser record);
}