package com.bruce.geekway.model;

import java.util.Date;

public class ItoProductBg {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_product_bg.id
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_product_bg.title
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_product_bg.description
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_product_bg.cover_thumb_pic_url
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	private String coverThumbPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_product_bg.cover_pic_url
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	private String coverPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_product_bg.create_time
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_product_bg.update_time
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_product_bg.id
	 * @return  the value of ito_product_bg.id
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_product_bg.id
	 * @param id  the value for ito_product_bg.id
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_product_bg.title
	 * @return  the value of ito_product_bg.title
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_product_bg.title
	 * @param title  the value for ito_product_bg.title
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_product_bg.description
	 * @return  the value of ito_product_bg.description
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_product_bg.description
	 * @param description  the value for ito_product_bg.description
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_product_bg.cover_thumb_pic_url
	 * @return  the value of ito_product_bg.cover_thumb_pic_url
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public String getCoverThumbPicUrl() {
		return coverThumbPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_product_bg.cover_thumb_pic_url
	 * @param coverThumbPicUrl  the value for ito_product_bg.cover_thumb_pic_url
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public void setCoverThumbPicUrl(String coverThumbPicUrl) {
		this.coverThumbPicUrl = coverThumbPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_product_bg.cover_pic_url
	 * @return  the value of ito_product_bg.cover_pic_url
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public String getCoverPicUrl() {
		return coverPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_product_bg.cover_pic_url
	 * @param coverPicUrl  the value for ito_product_bg.cover_pic_url
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public void setCoverPicUrl(String coverPicUrl) {
		this.coverPicUrl = coverPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_product_bg.create_time
	 * @return  the value of ito_product_bg.create_time
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_product_bg.create_time
	 * @param createTime  the value for ito_product_bg.create_time
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_product_bg.update_time
	 * @return  the value of ito_product_bg.update_time
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_product_bg.update_time
	 * @param updateTime  the value for ito_product_bg.update_time
	 * @mbggenerated  Sun Jun 15 13:44:55 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}