package com.bruce.geekway.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ItoSkuCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	protected Integer limitOffset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	protected Integer limitRows;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public ItoSkuCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setLimitOffset(Integer limitOffset) {
		this.limitOffset = limitOffset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Integer getLimitOffset() {
		return limitOffset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setLimitRows(Integer limitRows) {
		this.limitRows = limitRows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Integer getLimitRows() {
		return limitRows;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNull() {
			addCriterion("product_id is null");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("product_id is not null");
			return (Criteria) this;
		}

		public Criteria andProductIdEqualTo(Integer value) {
			addCriterion("product_id =", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotEqualTo(Integer value) {
			addCriterion("product_id <>", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThan(Integer value) {
			addCriterion("product_id >", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("product_id >=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThan(Integer value) {
			addCriterion("product_id <", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThanOrEqualTo(Integer value) {
			addCriterion("product_id <=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdIn(List<Integer> values) {
			addCriterion("product_id in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotIn(List<Integer> values) {
			addCriterion("product_id not in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdBetween(Integer value1, Integer value2) {
			addCriterion("product_id between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
			addCriterion("product_id not between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andOutIdIsNull() {
			addCriterion("out_id is null");
			return (Criteria) this;
		}

		public Criteria andOutIdIsNotNull() {
			addCriterion("out_id is not null");
			return (Criteria) this;
		}

		public Criteria andOutIdEqualTo(String value) {
			addCriterion("out_id =", value, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdNotEqualTo(String value) {
			addCriterion("out_id <>", value, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdGreaterThan(String value) {
			addCriterion("out_id >", value, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdGreaterThanOrEqualTo(String value) {
			addCriterion("out_id >=", value, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdLessThan(String value) {
			addCriterion("out_id <", value, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdLessThanOrEqualTo(String value) {
			addCriterion("out_id <=", value, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdLike(String value) {
			addCriterion("out_id like", value, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdNotLike(String value) {
			addCriterion("out_id not like", value, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdIn(List<String> values) {
			addCriterion("out_id in", values, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdNotIn(List<String> values) {
			addCriterion("out_id not in", values, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdBetween(String value1, String value2) {
			addCriterion("out_id between", value1, value2, "outId");
			return (Criteria) this;
		}

		public Criteria andOutIdNotBetween(String value1, String value2) {
			addCriterion("out_id not between", value1, value2, "outId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameIsNull() {
			addCriterion("properties_name is null");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameIsNotNull() {
			addCriterion("properties_name is not null");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameEqualTo(String value) {
			addCriterion("properties_name =", value, "propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameNotEqualTo(String value) {
			addCriterion("properties_name <>", value, "propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameGreaterThan(String value) {
			addCriterion("properties_name >", value, "propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameGreaterThanOrEqualTo(String value) {
			addCriterion("properties_name >=", value, "propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameLessThan(String value) {
			addCriterion("properties_name <", value, "propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameLessThanOrEqualTo(String value) {
			addCriterion("properties_name <=", value, "propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameLike(String value) {
			addCriterion("properties_name like", value, "propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameNotLike(String value) {
			addCriterion("properties_name not like", value, "propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameIn(List<String> values) {
			addCriterion("properties_name in", values, "propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameNotIn(List<String> values) {
			addCriterion("properties_name not in", values, "propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameBetween(String value1, String value2) {
			addCriterion("properties_name between", value1, value2,
					"propertiesName");
			return (Criteria) this;
		}

		public Criteria andPropertiesNameNotBetween(String value1, String value2) {
			addCriterion("properties_name not between", value1, value2,
					"propertiesName");
			return (Criteria) this;
		}

		public Criteria andNumIsNull() {
			addCriterion("num is null");
			return (Criteria) this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("num is not null");
			return (Criteria) this;
		}

		public Criteria andNumEqualTo(Integer value) {
			addCriterion("num =", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotEqualTo(Integer value) {
			addCriterion("num <>", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThan(Integer value) {
			addCriterion("num >", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("num >=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThan(Integer value) {
			addCriterion("num <", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThanOrEqualTo(Integer value) {
			addCriterion("num <=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumIn(List<Integer> values) {
			addCriterion("num in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotIn(List<Integer> values) {
			addCriterion("num not in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumBetween(Integer value1, Integer value2) {
			addCriterion("num between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotBetween(Integer value1, Integer value2) {
			addCriterion("num not between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andOriginPriceIsNull() {
			addCriterion("origin_price is null");
			return (Criteria) this;
		}

		public Criteria andOriginPriceIsNotNull() {
			addCriterion("origin_price is not null");
			return (Criteria) this;
		}

		public Criteria andOriginPriceEqualTo(Double value) {
			addCriterion("origin_price =", value, "originPrice");
			return (Criteria) this;
		}

		public Criteria andOriginPriceNotEqualTo(Double value) {
			addCriterion("origin_price <>", value, "originPrice");
			return (Criteria) this;
		}

		public Criteria andOriginPriceGreaterThan(Double value) {
			addCriterion("origin_price >", value, "originPrice");
			return (Criteria) this;
		}

		public Criteria andOriginPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("origin_price >=", value, "originPrice");
			return (Criteria) this;
		}

		public Criteria andOriginPriceLessThan(Double value) {
			addCriterion("origin_price <", value, "originPrice");
			return (Criteria) this;
		}

		public Criteria andOriginPriceLessThanOrEqualTo(Double value) {
			addCriterion("origin_price <=", value, "originPrice");
			return (Criteria) this;
		}

		public Criteria andOriginPriceIn(List<Double> values) {
			addCriterion("origin_price in", values, "originPrice");
			return (Criteria) this;
		}

		public Criteria andOriginPriceNotIn(List<Double> values) {
			addCriterion("origin_price not in", values, "originPrice");
			return (Criteria) this;
		}

		public Criteria andOriginPriceBetween(Double value1, Double value2) {
			addCriterion("origin_price between", value1, value2, "originPrice");
			return (Criteria) this;
		}

		public Criteria andOriginPriceNotBetween(Double value1, Double value2) {
			addCriterion("origin_price not between", value1, value2,
					"originPrice");
			return (Criteria) this;
		}

		public Criteria andPriceIsNull() {
			addCriterion("price is null");
			return (Criteria) this;
		}

		public Criteria andPriceIsNotNull() {
			addCriterion("price is not null");
			return (Criteria) this;
		}

		public Criteria andPriceEqualTo(Double value) {
			addCriterion("price =", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotEqualTo(Double value) {
			addCriterion("price <>", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThan(Double value) {
			addCriterion("price >", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceGreaterThanOrEqualTo(Double value) {
			addCriterion("price >=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThan(Double value) {
			addCriterion("price <", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceLessThanOrEqualTo(Double value) {
			addCriterion("price <=", value, "price");
			return (Criteria) this;
		}

		public Criteria andPriceIn(List<Double> values) {
			addCriterion("price in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotIn(List<Double> values) {
			addCriterion("price not in", values, "price");
			return (Criteria) this;
		}

		public Criteria andPriceBetween(Double value1, Double value2) {
			addCriterion("price between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andPriceNotBetween(Double value1, Double value2) {
			addCriterion("price not between", value1, value2, "price");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlIsNull() {
			addCriterion("sku_pic_url is null");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlIsNotNull() {
			addCriterion("sku_pic_url is not null");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlEqualTo(String value) {
			addCriterion("sku_pic_url =", value, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlNotEqualTo(String value) {
			addCriterion("sku_pic_url <>", value, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlGreaterThan(String value) {
			addCriterion("sku_pic_url >", value, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlGreaterThanOrEqualTo(String value) {
			addCriterion("sku_pic_url >=", value, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlLessThan(String value) {
			addCriterion("sku_pic_url <", value, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlLessThanOrEqualTo(String value) {
			addCriterion("sku_pic_url <=", value, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlLike(String value) {
			addCriterion("sku_pic_url like", value, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlNotLike(String value) {
			addCriterion("sku_pic_url not like", value, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlIn(List<String> values) {
			addCriterion("sku_pic_url in", values, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlNotIn(List<String> values) {
			addCriterion("sku_pic_url not in", values, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlBetween(String value1, String value2) {
			addCriterion("sku_pic_url between", value1, value2, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuPicUrlNotBetween(String value1, String value2) {
			addCriterion("sku_pic_url not between", value1, value2, "skuPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlIsNull() {
			addCriterion("sku_thumb_pic_url is null");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlIsNotNull() {
			addCriterion("sku_thumb_pic_url is not null");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlEqualTo(String value) {
			addCriterion("sku_thumb_pic_url =", value, "skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlNotEqualTo(String value) {
			addCriterion("sku_thumb_pic_url <>", value, "skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlGreaterThan(String value) {
			addCriterion("sku_thumb_pic_url >", value, "skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlGreaterThanOrEqualTo(String value) {
			addCriterion("sku_thumb_pic_url >=", value, "skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlLessThan(String value) {
			addCriterion("sku_thumb_pic_url <", value, "skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlLessThanOrEqualTo(String value) {
			addCriterion("sku_thumb_pic_url <=", value, "skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlLike(String value) {
			addCriterion("sku_thumb_pic_url like", value, "skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlNotLike(String value) {
			addCriterion("sku_thumb_pic_url not like", value, "skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlIn(List<String> values) {
			addCriterion("sku_thumb_pic_url in", values, "skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlNotIn(List<String> values) {
			addCriterion("sku_thumb_pic_url not in", values, "skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlBetween(String value1, String value2) {
			addCriterion("sku_thumb_pic_url between", value1, value2,
					"skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andSkuThumbPicUrlNotBetween(String value1, String value2) {
			addCriterion("sku_thumb_pic_url not between", value1, value2,
					"skuThumbPicUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlIsNull() {
			addCriterion("buy_url is null");
			return (Criteria) this;
		}

		public Criteria andBuyUrlIsNotNull() {
			addCriterion("buy_url is not null");
			return (Criteria) this;
		}

		public Criteria andBuyUrlEqualTo(String value) {
			addCriterion("buy_url =", value, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlNotEqualTo(String value) {
			addCriterion("buy_url <>", value, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlGreaterThan(String value) {
			addCriterion("buy_url >", value, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlGreaterThanOrEqualTo(String value) {
			addCriterion("buy_url >=", value, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlLessThan(String value) {
			addCriterion("buy_url <", value, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlLessThanOrEqualTo(String value) {
			addCriterion("buy_url <=", value, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlLike(String value) {
			addCriterion("buy_url like", value, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlNotLike(String value) {
			addCriterion("buy_url not like", value, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlIn(List<String> values) {
			addCriterion("buy_url in", values, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlNotIn(List<String> values) {
			addCriterion("buy_url not in", values, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlBetween(String value1, String value2) {
			addCriterion("buy_url between", value1, value2, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andBuyUrlNotBetween(String value1, String value2) {
			addCriterion("buy_url not between", value1, value2, "buyUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlIsNull() {
			addCriterion("alipay_sku_url is null");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlIsNotNull() {
			addCriterion("alipay_sku_url is not null");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlEqualTo(String value) {
			addCriterion("alipay_sku_url =", value, "alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlNotEqualTo(String value) {
			addCriterion("alipay_sku_url <>", value, "alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlGreaterThan(String value) {
			addCriterion("alipay_sku_url >", value, "alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlGreaterThanOrEqualTo(String value) {
			addCriterion("alipay_sku_url >=", value, "alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlLessThan(String value) {
			addCriterion("alipay_sku_url <", value, "alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlLessThanOrEqualTo(String value) {
			addCriterion("alipay_sku_url <=", value, "alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlLike(String value) {
			addCriterion("alipay_sku_url like", value, "alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlNotLike(String value) {
			addCriterion("alipay_sku_url not like", value, "alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlIn(List<String> values) {
			addCriterion("alipay_sku_url in", values, "alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlNotIn(List<String> values) {
			addCriterion("alipay_sku_url not in", values, "alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlBetween(String value1, String value2) {
			addCriterion("alipay_sku_url between", value1, value2,
					"alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andAlipaySkuUrlNotBetween(String value1, String value2) {
			addCriterion("alipay_sku_url not between", value1, value2,
					"alipaySkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlIsNull() {
			addCriterion("koudaitong_sku_url is null");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlIsNotNull() {
			addCriterion("koudaitong_sku_url is not null");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlEqualTo(String value) {
			addCriterion("koudaitong_sku_url =", value, "koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlNotEqualTo(String value) {
			addCriterion("koudaitong_sku_url <>", value, "koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlGreaterThan(String value) {
			addCriterion("koudaitong_sku_url >", value, "koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlGreaterThanOrEqualTo(String value) {
			addCriterion("koudaitong_sku_url >=", value, "koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlLessThan(String value) {
			addCriterion("koudaitong_sku_url <", value, "koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlLessThanOrEqualTo(String value) {
			addCriterion("koudaitong_sku_url <=", value, "koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlLike(String value) {
			addCriterion("koudaitong_sku_url like", value, "koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlNotLike(String value) {
			addCriterion("koudaitong_sku_url not like", value,
					"koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlIn(List<String> values) {
			addCriterion("koudaitong_sku_url in", values, "koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlNotIn(List<String> values) {
			addCriterion("koudaitong_sku_url not in", values,
					"koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlBetween(String value1, String value2) {
			addCriterion("koudaitong_sku_url between", value1, value2,
					"koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andKoudaitongSkuUrlNotBetween(String value1,
				String value2) {
			addCriterion("koudaitong_sku_url not between", value1, value2,
					"koudaitongSkuUrl");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andMaterialIdIsNull() {
			addCriterion("material_id is null");
			return (Criteria) this;
		}

		public Criteria andMaterialIdIsNotNull() {
			addCriterion("material_id is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialIdEqualTo(Integer value) {
			addCriterion("material_id =", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotEqualTo(Integer value) {
			addCriterion("material_id <>", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdGreaterThan(Integer value) {
			addCriterion("material_id >", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("material_id >=", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdLessThan(Integer value) {
			addCriterion("material_id <", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdLessThanOrEqualTo(Integer value) {
			addCriterion("material_id <=", value, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdIn(List<Integer> values) {
			addCriterion("material_id in", values, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotIn(List<Integer> values) {
			addCriterion("material_id not in", values, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdBetween(Integer value1, Integer value2) {
			addCriterion("material_id between", value1, value2, "materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialIdNotBetween(Integer value1, Integer value2) {
			addCriterion("material_id not between", value1, value2,
					"materialId");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlIsNull() {
			addCriterion("material_pic_url is null");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlIsNotNull() {
			addCriterion("material_pic_url is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlEqualTo(String value) {
			addCriterion("material_pic_url =", value, "materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlNotEqualTo(String value) {
			addCriterion("material_pic_url <>", value, "materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlGreaterThan(String value) {
			addCriterion("material_pic_url >", value, "materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlGreaterThanOrEqualTo(String value) {
			addCriterion("material_pic_url >=", value, "materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlLessThan(String value) {
			addCriterion("material_pic_url <", value, "materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlLessThanOrEqualTo(String value) {
			addCriterion("material_pic_url <=", value, "materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlLike(String value) {
			addCriterion("material_pic_url like", value, "materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlNotLike(String value) {
			addCriterion("material_pic_url not like", value, "materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlIn(List<String> values) {
			addCriterion("material_pic_url in", values, "materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlNotIn(List<String> values) {
			addCriterion("material_pic_url not in", values, "materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlBetween(String value1, String value2) {
			addCriterion("material_pic_url between", value1, value2,
					"materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andMaterialPicUrlNotBetween(String value1, String value2) {
			addCriterion("material_pic_url not between", value1, value2,
					"materialPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorIdIsNull() {
			addCriterion("color_id is null");
			return (Criteria) this;
		}

		public Criteria andColorIdIsNotNull() {
			addCriterion("color_id is not null");
			return (Criteria) this;
		}

		public Criteria andColorIdEqualTo(Integer value) {
			addCriterion("color_id =", value, "colorId");
			return (Criteria) this;
		}

		public Criteria andColorIdNotEqualTo(Integer value) {
			addCriterion("color_id <>", value, "colorId");
			return (Criteria) this;
		}

		public Criteria andColorIdGreaterThan(Integer value) {
			addCriterion("color_id >", value, "colorId");
			return (Criteria) this;
		}

		public Criteria andColorIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("color_id >=", value, "colorId");
			return (Criteria) this;
		}

		public Criteria andColorIdLessThan(Integer value) {
			addCriterion("color_id <", value, "colorId");
			return (Criteria) this;
		}

		public Criteria andColorIdLessThanOrEqualTo(Integer value) {
			addCriterion("color_id <=", value, "colorId");
			return (Criteria) this;
		}

		public Criteria andColorIdIn(List<Integer> values) {
			addCriterion("color_id in", values, "colorId");
			return (Criteria) this;
		}

		public Criteria andColorIdNotIn(List<Integer> values) {
			addCriterion("color_id not in", values, "colorId");
			return (Criteria) this;
		}

		public Criteria andColorIdBetween(Integer value1, Integer value2) {
			addCriterion("color_id between", value1, value2, "colorId");
			return (Criteria) this;
		}

		public Criteria andColorIdNotBetween(Integer value1, Integer value2) {
			addCriterion("color_id not between", value1, value2, "colorId");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlIsNull() {
			addCriterion("color_pic_url is null");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlIsNotNull() {
			addCriterion("color_pic_url is not null");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlEqualTo(String value) {
			addCriterion("color_pic_url =", value, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlNotEqualTo(String value) {
			addCriterion("color_pic_url <>", value, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlGreaterThan(String value) {
			addCriterion("color_pic_url >", value, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlGreaterThanOrEqualTo(String value) {
			addCriterion("color_pic_url >=", value, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlLessThan(String value) {
			addCriterion("color_pic_url <", value, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlLessThanOrEqualTo(String value) {
			addCriterion("color_pic_url <=", value, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlLike(String value) {
			addCriterion("color_pic_url like", value, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlNotLike(String value) {
			addCriterion("color_pic_url not like", value, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlIn(List<String> values) {
			addCriterion("color_pic_url in", values, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlNotIn(List<String> values) {
			addCriterion("color_pic_url not in", values, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlBetween(String value1, String value2) {
			addCriterion("color_pic_url between", value1, value2, "colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andColorPicUrlNotBetween(String value1, String value2) {
			addCriterion("color_pic_url not between", value1, value2,
					"colorPicUrl");
			return (Criteria) this;
		}

		public Criteria andSizeIdIsNull() {
			addCriterion("size_id is null");
			return (Criteria) this;
		}

		public Criteria andSizeIdIsNotNull() {
			addCriterion("size_id is not null");
			return (Criteria) this;
		}

		public Criteria andSizeIdEqualTo(Integer value) {
			addCriterion("size_id =", value, "sizeId");
			return (Criteria) this;
		}

		public Criteria andSizeIdNotEqualTo(Integer value) {
			addCriterion("size_id <>", value, "sizeId");
			return (Criteria) this;
		}

		public Criteria andSizeIdGreaterThan(Integer value) {
			addCriterion("size_id >", value, "sizeId");
			return (Criteria) this;
		}

		public Criteria andSizeIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("size_id >=", value, "sizeId");
			return (Criteria) this;
		}

		public Criteria andSizeIdLessThan(Integer value) {
			addCriterion("size_id <", value, "sizeId");
			return (Criteria) this;
		}

		public Criteria andSizeIdLessThanOrEqualTo(Integer value) {
			addCriterion("size_id <=", value, "sizeId");
			return (Criteria) this;
		}

		public Criteria andSizeIdIn(List<Integer> values) {
			addCriterion("size_id in", values, "sizeId");
			return (Criteria) this;
		}

		public Criteria andSizeIdNotIn(List<Integer> values) {
			addCriterion("size_id not in", values, "sizeId");
			return (Criteria) this;
		}

		public Criteria andSizeIdBetween(Integer value1, Integer value2) {
			addCriterion("size_id between", value1, value2, "sizeId");
			return (Criteria) this;
		}

		public Criteria andSizeIdNotBetween(Integer value1, Integer value2) {
			addCriterion("size_id not between", value1, value2, "sizeId");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlIsNull() {
			addCriterion("size_pic_url is null");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlIsNotNull() {
			addCriterion("size_pic_url is not null");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlEqualTo(String value) {
			addCriterion("size_pic_url =", value, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlNotEqualTo(String value) {
			addCriterion("size_pic_url <>", value, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlGreaterThan(String value) {
			addCriterion("size_pic_url >", value, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlGreaterThanOrEqualTo(String value) {
			addCriterion("size_pic_url >=", value, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlLessThan(String value) {
			addCriterion("size_pic_url <", value, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlLessThanOrEqualTo(String value) {
			addCriterion("size_pic_url <=", value, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlLike(String value) {
			addCriterion("size_pic_url like", value, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlNotLike(String value) {
			addCriterion("size_pic_url not like", value, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlIn(List<String> values) {
			addCriterion("size_pic_url in", values, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlNotIn(List<String> values) {
			addCriterion("size_pic_url not in", values, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlBetween(String value1, String value2) {
			addCriterion("size_pic_url between", value1, value2, "sizePicUrl");
			return (Criteria) this;
		}

		public Criteria andSizePicUrlNotBetween(String value1, String value2) {
			addCriterion("size_pic_url not between", value1, value2,
					"sizePicUrl");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ito_sku
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ito_sku
     *
     * @mbggenerated do_not_delete_during_merge Fri May 02 22:42:49 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}