package com.bruce.geekway.model;

import java.util.Date;

public class ItoSkuProp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku_prop.id
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku_prop.name
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku_prop.description
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku_prop.create_time
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku_prop.update_time
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku_prop.id
	 * @return  the value of ito_sku_prop.id
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku_prop.id
	 * @param id  the value for ito_sku_prop.id
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku_prop.name
	 * @return  the value of ito_sku_prop.name
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku_prop.name
	 * @param name  the value for ito_sku_prop.name
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku_prop.description
	 * @return  the value of ito_sku_prop.description
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku_prop.description
	 * @param description  the value for ito_sku_prop.description
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku_prop.create_time
	 * @return  the value of ito_sku_prop.create_time
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku_prop.create_time
	 * @param createTime  the value for ito_sku_prop.create_time
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku_prop.update_time
	 * @return  the value of ito_sku_prop.update_time
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku_prop.update_time
	 * @param updateTime  the value for ito_sku_prop.update_time
	 * @mbggenerated  Sat May 03 14:51:30 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}