package com.bruce.geekway.model;

import java.util.Date;

public class ItoSku extends ItoSkuBase{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.product_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.out_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String outId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.name
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.properties_name
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String propertiesName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.num
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.origin_price
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private Double originPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.price
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.sku_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String skuPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.sku_thumb_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String skuThumbPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.buy_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String buyUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.alipay_sku_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String alipaySkuUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.koudaitong_sku_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String koudaitongSkuUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.create_time
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.update_time
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.material_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private Integer materialId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.material_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String materialPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.color_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private Integer colorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.color_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String colorPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.size_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private Integer sizeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ito_sku.size_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	private String sizePicUrl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.id
	 * @return  the value of ito_sku.id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.id
	 * @param id  the value for ito_sku.id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.product_id
	 * @return  the value of ito_sku.product_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.product_id
	 * @param productId  the value for ito_sku.product_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.out_id
	 * @return  the value of ito_sku.out_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getOutId() {
		return outId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.out_id
	 * @param outId  the value for ito_sku.out_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setOutId(String outId) {
		this.outId = outId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.name
	 * @return  the value of ito_sku.name
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.name
	 * @param name  the value for ito_sku.name
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.properties_name
	 * @return  the value of ito_sku.properties_name
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getPropertiesName() {
		return propertiesName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.properties_name
	 * @param propertiesName  the value for ito_sku.properties_name
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setPropertiesName(String propertiesName) {
		this.propertiesName = propertiesName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.num
	 * @return  the value of ito_sku.num
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.num
	 * @param num  the value for ito_sku.num
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.origin_price
	 * @return  the value of ito_sku.origin_price
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Double getOriginPrice() {
		return originPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.origin_price
	 * @param originPrice  the value for ito_sku.origin_price
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setOriginPrice(Double originPrice) {
		this.originPrice = originPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.price
	 * @return  the value of ito_sku.price
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.price
	 * @param price  the value for ito_sku.price
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.sku_pic_url
	 * @return  the value of ito_sku.sku_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getSkuPicUrl() {
		return skuPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.sku_pic_url
	 * @param skuPicUrl  the value for ito_sku.sku_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setSkuPicUrl(String skuPicUrl) {
		this.skuPicUrl = skuPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.sku_thumb_pic_url
	 * @return  the value of ito_sku.sku_thumb_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getSkuThumbPicUrl() {
		return skuThumbPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.sku_thumb_pic_url
	 * @param skuThumbPicUrl  the value for ito_sku.sku_thumb_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setSkuThumbPicUrl(String skuThumbPicUrl) {
		this.skuThumbPicUrl = skuThumbPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.buy_url
	 * @return  the value of ito_sku.buy_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getBuyUrl() {
		return buyUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.buy_url
	 * @param buyUrl  the value for ito_sku.buy_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setBuyUrl(String buyUrl) {
		this.buyUrl = buyUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.alipay_sku_url
	 * @return  the value of ito_sku.alipay_sku_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getAlipaySkuUrl() {
		return alipaySkuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.alipay_sku_url
	 * @param alipaySkuUrl  the value for ito_sku.alipay_sku_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setAlipaySkuUrl(String alipaySkuUrl) {
		this.alipaySkuUrl = alipaySkuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.koudaitong_sku_url
	 * @return  the value of ito_sku.koudaitong_sku_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getKoudaitongSkuUrl() {
		return koudaitongSkuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.koudaitong_sku_url
	 * @param koudaitongSkuUrl  the value for ito_sku.koudaitong_sku_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setKoudaitongSkuUrl(String koudaitongSkuUrl) {
		this.koudaitongSkuUrl = koudaitongSkuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.create_time
	 * @return  the value of ito_sku.create_time
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.create_time
	 * @param createTime  the value for ito_sku.create_time
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.update_time
	 * @return  the value of ito_sku.update_time
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.update_time
	 * @param updateTime  the value for ito_sku.update_time
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.material_id
	 * @return  the value of ito_sku.material_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Integer getMaterialId() {
		return materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.material_id
	 * @param materialId  the value for ito_sku.material_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setMaterialId(Integer materialId) {
		this.materialId = materialId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.material_pic_url
	 * @return  the value of ito_sku.material_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getMaterialPicUrl() {
		return materialPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.material_pic_url
	 * @param materialPicUrl  the value for ito_sku.material_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setMaterialPicUrl(String materialPicUrl) {
		this.materialPicUrl = materialPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.color_id
	 * @return  the value of ito_sku.color_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Integer getColorId() {
		return colorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.color_id
	 * @param colorId  the value for ito_sku.color_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setColorId(Integer colorId) {
		this.colorId = colorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.color_pic_url
	 * @return  the value of ito_sku.color_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getColorPicUrl() {
		return colorPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.color_pic_url
	 * @param colorPicUrl  the value for ito_sku.color_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setColorPicUrl(String colorPicUrl) {
		this.colorPicUrl = colorPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.size_id
	 * @return  the value of ito_sku.size_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public Integer getSizeId() {
		return sizeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.size_id
	 * @param sizeId  the value for ito_sku.size_id
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setSizeId(Integer sizeId) {
		this.sizeId = sizeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ito_sku.size_pic_url
	 * @return  the value of ito_sku.size_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public String getSizePicUrl() {
		return sizePicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ito_sku.size_pic_url
	 * @param sizePicUrl  the value for ito_sku.size_pic_url
	 * @mbggenerated  Sun Dec 28 09:57:52 CST 2014
	 */
	public void setSizePicUrl(String sizePicUrl) {
		this.sizePicUrl = sizePicUrl;
	}
}