package com.bruce.geekway.model;

import java.util.Date;

public class KlhProductOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.id
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.user_openid
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private String userOpenid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.product_id
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.title
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.description
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.num
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private Integer num;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.score
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private Integer score;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.post_sn
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private String postSn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.post_name
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private String postName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.post_code
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.post_address
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private String postAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.post_mobile
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private String postMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.post_email
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private String postEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.post_status
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private Short postStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.status
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.create_time
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_product_order.update_time
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.id
	 * @return  the value of klh_product_order.id
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.id
	 * @param id  the value for klh_product_order.id
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.user_openid
	 * @return  the value of klh_product_order.user_openid
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public String getUserOpenid() {
		return userOpenid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.user_openid
	 * @param userOpenid  the value for klh_product_order.user_openid
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setUserOpenid(String userOpenid) {
		this.userOpenid = userOpenid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.product_id
	 * @return  the value of klh_product_order.product_id
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.product_id
	 * @param productId  the value for klh_product_order.product_id
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.title
	 * @return  the value of klh_product_order.title
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.title
	 * @param title  the value for klh_product_order.title
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.description
	 * @return  the value of klh_product_order.description
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.description
	 * @param description  the value for klh_product_order.description
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.num
	 * @return  the value of klh_product_order.num
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Integer getNum() {
		return num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.num
	 * @param num  the value for klh_product_order.num
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setNum(Integer num) {
		this.num = num;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.score
	 * @return  the value of klh_product_order.score
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Integer getScore() {
		return score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.score
	 * @param score  the value for klh_product_order.score
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setScore(Integer score) {
		this.score = score;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.post_sn
	 * @return  the value of klh_product_order.post_sn
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public String getPostSn() {
		return postSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.post_sn
	 * @param postSn  the value for klh_product_order.post_sn
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setPostSn(String postSn) {
		this.postSn = postSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.post_name
	 * @return  the value of klh_product_order.post_name
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public String getPostName() {
		return postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.post_name
	 * @param postName  the value for klh_product_order.post_name
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setPostName(String postName) {
		this.postName = postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.post_code
	 * @return  the value of klh_product_order.post_code
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.post_code
	 * @param postCode  the value for klh_product_order.post_code
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.post_address
	 * @return  the value of klh_product_order.post_address
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public String getPostAddress() {
		return postAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.post_address
	 * @param postAddress  the value for klh_product_order.post_address
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setPostAddress(String postAddress) {
		this.postAddress = postAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.post_mobile
	 * @return  the value of klh_product_order.post_mobile
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public String getPostMobile() {
		return postMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.post_mobile
	 * @param postMobile  the value for klh_product_order.post_mobile
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setPostMobile(String postMobile) {
		this.postMobile = postMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.post_email
	 * @return  the value of klh_product_order.post_email
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public String getPostEmail() {
		return postEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.post_email
	 * @param postEmail  the value for klh_product_order.post_email
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setPostEmail(String postEmail) {
		this.postEmail = postEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.post_status
	 * @return  the value of klh_product_order.post_status
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Short getPostStatus() {
		return postStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.post_status
	 * @param postStatus  the value for klh_product_order.post_status
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setPostStatus(Short postStatus) {
		this.postStatus = postStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.status
	 * @return  the value of klh_product_order.status
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.status
	 * @param status  the value for klh_product_order.status
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.create_time
	 * @return  the value of klh_product_order.create_time
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.create_time
	 * @param createTime  the value for klh_product_order.create_time
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_product_order.update_time
	 * @return  the value of klh_product_order.update_time
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_product_order.update_time
	 * @param updateTime  the value for klh_product_order.update_time
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}