package com.bruce.geekway.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class KlhProductOrderCriteria {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	protected List<Criteria> oredCriteria;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	protected Integer limitOffset;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	protected Integer limitRows;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public KlhProductOrderCriteria() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setLimitOffset(Integer limitOffset) {
		this.limitOffset = limitOffset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Integer getLimitOffset() {
		return limitOffset;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public void setLimitRows(Integer limitRows) {
		this.limitRows = limitRows;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public Integer getLimitRows() {
		return limitRows;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andUserOpenidIsNull() {
			addCriterion("user_openid is null");
			return (Criteria) this;
		}

		public Criteria andUserOpenidIsNotNull() {
			addCriterion("user_openid is not null");
			return (Criteria) this;
		}

		public Criteria andUserOpenidEqualTo(String value) {
			addCriterion("user_openid =", value, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidNotEqualTo(String value) {
			addCriterion("user_openid <>", value, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidGreaterThan(String value) {
			addCriterion("user_openid >", value, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidGreaterThanOrEqualTo(String value) {
			addCriterion("user_openid >=", value, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidLessThan(String value) {
			addCriterion("user_openid <", value, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidLessThanOrEqualTo(String value) {
			addCriterion("user_openid <=", value, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidLike(String value) {
			addCriterion("user_openid like", value, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidNotLike(String value) {
			addCriterion("user_openid not like", value, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidIn(List<String> values) {
			addCriterion("user_openid in", values, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidNotIn(List<String> values) {
			addCriterion("user_openid not in", values, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidBetween(String value1, String value2) {
			addCriterion("user_openid between", value1, value2, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andUserOpenidNotBetween(String value1, String value2) {
			addCriterion("user_openid not between", value1, value2, "userOpenid");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNull() {
			addCriterion("product_id is null");
			return (Criteria) this;
		}

		public Criteria andProductIdIsNotNull() {
			addCriterion("product_id is not null");
			return (Criteria) this;
		}

		public Criteria andProductIdEqualTo(Integer value) {
			addCriterion("product_id =", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotEqualTo(Integer value) {
			addCriterion("product_id <>", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThan(Integer value) {
			addCriterion("product_id >", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("product_id >=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThan(Integer value) {
			addCriterion("product_id <", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdLessThanOrEqualTo(Integer value) {
			addCriterion("product_id <=", value, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdIn(List<Integer> values) {
			addCriterion("product_id in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotIn(List<Integer> values) {
			addCriterion("product_id not in", values, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdBetween(Integer value1, Integer value2) {
			addCriterion("product_id between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andProductIdNotBetween(Integer value1, Integer value2) {
			addCriterion("product_id not between", value1, value2, "productId");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNull() {
			addCriterion("description is null");
			return (Criteria) this;
		}

		public Criteria andDescriptionIsNotNull() {
			addCriterion("description is not null");
			return (Criteria) this;
		}

		public Criteria andDescriptionEqualTo(String value) {
			addCriterion("description =", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotEqualTo(String value) {
			addCriterion("description <>", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThan(String value) {
			addCriterion("description >", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
			addCriterion("description >=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThan(String value) {
			addCriterion("description <", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLessThanOrEqualTo(String value) {
			addCriterion("description <=", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionLike(String value) {
			addCriterion("description like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotLike(String value) {
			addCriterion("description not like", value, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionIn(List<String> values) {
			addCriterion("description in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotIn(List<String> values) {
			addCriterion("description not in", values, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionBetween(String value1, String value2) {
			addCriterion("description between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andDescriptionNotBetween(String value1, String value2) {
			addCriterion("description not between", value1, value2, "description");
			return (Criteria) this;
		}

		public Criteria andNumIsNull() {
			addCriterion("num is null");
			return (Criteria) this;
		}

		public Criteria andNumIsNotNull() {
			addCriterion("num is not null");
			return (Criteria) this;
		}

		public Criteria andNumEqualTo(Integer value) {
			addCriterion("num =", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotEqualTo(Integer value) {
			addCriterion("num <>", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThan(Integer value) {
			addCriterion("num >", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("num >=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThan(Integer value) {
			addCriterion("num <", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumLessThanOrEqualTo(Integer value) {
			addCriterion("num <=", value, "num");
			return (Criteria) this;
		}

		public Criteria andNumIn(List<Integer> values) {
			addCriterion("num in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotIn(List<Integer> values) {
			addCriterion("num not in", values, "num");
			return (Criteria) this;
		}

		public Criteria andNumBetween(Integer value1, Integer value2) {
			addCriterion("num between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andNumNotBetween(Integer value1, Integer value2) {
			addCriterion("num not between", value1, value2, "num");
			return (Criteria) this;
		}

		public Criteria andScoreIsNull() {
			addCriterion("score is null");
			return (Criteria) this;
		}

		public Criteria andScoreIsNotNull() {
			addCriterion("score is not null");
			return (Criteria) this;
		}

		public Criteria andScoreEqualTo(Integer value) {
			addCriterion("score =", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotEqualTo(Integer value) {
			addCriterion("score <>", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThan(Integer value) {
			addCriterion("score >", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("score >=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThan(Integer value) {
			addCriterion("score <", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreLessThanOrEqualTo(Integer value) {
			addCriterion("score <=", value, "score");
			return (Criteria) this;
		}

		public Criteria andScoreIn(List<Integer> values) {
			addCriterion("score in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotIn(List<Integer> values) {
			addCriterion("score not in", values, "score");
			return (Criteria) this;
		}

		public Criteria andScoreBetween(Integer value1, Integer value2) {
			addCriterion("score between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("score not between", value1, value2, "score");
			return (Criteria) this;
		}

		public Criteria andPostSnIsNull() {
			addCriterion("post_sn is null");
			return (Criteria) this;
		}

		public Criteria andPostSnIsNotNull() {
			addCriterion("post_sn is not null");
			return (Criteria) this;
		}

		public Criteria andPostSnEqualTo(String value) {
			addCriterion("post_sn =", value, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnNotEqualTo(String value) {
			addCriterion("post_sn <>", value, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnGreaterThan(String value) {
			addCriterion("post_sn >", value, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnGreaterThanOrEqualTo(String value) {
			addCriterion("post_sn >=", value, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnLessThan(String value) {
			addCriterion("post_sn <", value, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnLessThanOrEqualTo(String value) {
			addCriterion("post_sn <=", value, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnLike(String value) {
			addCriterion("post_sn like", value, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnNotLike(String value) {
			addCriterion("post_sn not like", value, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnIn(List<String> values) {
			addCriterion("post_sn in", values, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnNotIn(List<String> values) {
			addCriterion("post_sn not in", values, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnBetween(String value1, String value2) {
			addCriterion("post_sn between", value1, value2, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostSnNotBetween(String value1, String value2) {
			addCriterion("post_sn not between", value1, value2, "postSn");
			return (Criteria) this;
		}

		public Criteria andPostNameIsNull() {
			addCriterion("post_name is null");
			return (Criteria) this;
		}

		public Criteria andPostNameIsNotNull() {
			addCriterion("post_name is not null");
			return (Criteria) this;
		}

		public Criteria andPostNameEqualTo(String value) {
			addCriterion("post_name =", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameNotEqualTo(String value) {
			addCriterion("post_name <>", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameGreaterThan(String value) {
			addCriterion("post_name >", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameGreaterThanOrEqualTo(String value) {
			addCriterion("post_name >=", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameLessThan(String value) {
			addCriterion("post_name <", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameLessThanOrEqualTo(String value) {
			addCriterion("post_name <=", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameLike(String value) {
			addCriterion("post_name like", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameNotLike(String value) {
			addCriterion("post_name not like", value, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameIn(List<String> values) {
			addCriterion("post_name in", values, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameNotIn(List<String> values) {
			addCriterion("post_name not in", values, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameBetween(String value1, String value2) {
			addCriterion("post_name between", value1, value2, "postName");
			return (Criteria) this;
		}

		public Criteria andPostNameNotBetween(String value1, String value2) {
			addCriterion("post_name not between", value1, value2, "postName");
			return (Criteria) this;
		}

		public Criteria andPostCodeIsNull() {
			addCriterion("post_code is null");
			return (Criteria) this;
		}

		public Criteria andPostCodeIsNotNull() {
			addCriterion("post_code is not null");
			return (Criteria) this;
		}

		public Criteria andPostCodeEqualTo(String value) {
			addCriterion("post_code =", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotEqualTo(String value) {
			addCriterion("post_code <>", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeGreaterThan(String value) {
			addCriterion("post_code >", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeGreaterThanOrEqualTo(String value) {
			addCriterion("post_code >=", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeLessThan(String value) {
			addCriterion("post_code <", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeLessThanOrEqualTo(String value) {
			addCriterion("post_code <=", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeLike(String value) {
			addCriterion("post_code like", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotLike(String value) {
			addCriterion("post_code not like", value, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeIn(List<String> values) {
			addCriterion("post_code in", values, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotIn(List<String> values) {
			addCriterion("post_code not in", values, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeBetween(String value1, String value2) {
			addCriterion("post_code between", value1, value2, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostCodeNotBetween(String value1, String value2) {
			addCriterion("post_code not between", value1, value2, "postCode");
			return (Criteria) this;
		}

		public Criteria andPostAddressIsNull() {
			addCriterion("post_address is null");
			return (Criteria) this;
		}

		public Criteria andPostAddressIsNotNull() {
			addCriterion("post_address is not null");
			return (Criteria) this;
		}

		public Criteria andPostAddressEqualTo(String value) {
			addCriterion("post_address =", value, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressNotEqualTo(String value) {
			addCriterion("post_address <>", value, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressGreaterThan(String value) {
			addCriterion("post_address >", value, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressGreaterThanOrEqualTo(String value) {
			addCriterion("post_address >=", value, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressLessThan(String value) {
			addCriterion("post_address <", value, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressLessThanOrEqualTo(String value) {
			addCriterion("post_address <=", value, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressLike(String value) {
			addCriterion("post_address like", value, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressNotLike(String value) {
			addCriterion("post_address not like", value, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressIn(List<String> values) {
			addCriterion("post_address in", values, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressNotIn(List<String> values) {
			addCriterion("post_address not in", values, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressBetween(String value1, String value2) {
			addCriterion("post_address between", value1, value2, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostAddressNotBetween(String value1, String value2) {
			addCriterion("post_address not between", value1, value2, "postAddress");
			return (Criteria) this;
		}

		public Criteria andPostMobileIsNull() {
			addCriterion("post_mobile is null");
			return (Criteria) this;
		}

		public Criteria andPostMobileIsNotNull() {
			addCriterion("post_mobile is not null");
			return (Criteria) this;
		}

		public Criteria andPostMobileEqualTo(String value) {
			addCriterion("post_mobile =", value, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileNotEqualTo(String value) {
			addCriterion("post_mobile <>", value, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileGreaterThan(String value) {
			addCriterion("post_mobile >", value, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileGreaterThanOrEqualTo(String value) {
			addCriterion("post_mobile >=", value, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileLessThan(String value) {
			addCriterion("post_mobile <", value, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileLessThanOrEqualTo(String value) {
			addCriterion("post_mobile <=", value, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileLike(String value) {
			addCriterion("post_mobile like", value, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileNotLike(String value) {
			addCriterion("post_mobile not like", value, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileIn(List<String> values) {
			addCriterion("post_mobile in", values, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileNotIn(List<String> values) {
			addCriterion("post_mobile not in", values, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileBetween(String value1, String value2) {
			addCriterion("post_mobile between", value1, value2, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostMobileNotBetween(String value1, String value2) {
			addCriterion("post_mobile not between", value1, value2, "postMobile");
			return (Criteria) this;
		}

		public Criteria andPostEmailIsNull() {
			addCriterion("post_email is null");
			return (Criteria) this;
		}

		public Criteria andPostEmailIsNotNull() {
			addCriterion("post_email is not null");
			return (Criteria) this;
		}

		public Criteria andPostEmailEqualTo(String value) {
			addCriterion("post_email =", value, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailNotEqualTo(String value) {
			addCriterion("post_email <>", value, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailGreaterThan(String value) {
			addCriterion("post_email >", value, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailGreaterThanOrEqualTo(String value) {
			addCriterion("post_email >=", value, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailLessThan(String value) {
			addCriterion("post_email <", value, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailLessThanOrEqualTo(String value) {
			addCriterion("post_email <=", value, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailLike(String value) {
			addCriterion("post_email like", value, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailNotLike(String value) {
			addCriterion("post_email not like", value, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailIn(List<String> values) {
			addCriterion("post_email in", values, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailNotIn(List<String> values) {
			addCriterion("post_email not in", values, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailBetween(String value1, String value2) {
			addCriterion("post_email between", value1, value2, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostEmailNotBetween(String value1, String value2) {
			addCriterion("post_email not between", value1, value2, "postEmail");
			return (Criteria) this;
		}

		public Criteria andPostStatusIsNull() {
			addCriterion("post_status is null");
			return (Criteria) this;
		}

		public Criteria andPostStatusIsNotNull() {
			addCriterion("post_status is not null");
			return (Criteria) this;
		}

		public Criteria andPostStatusEqualTo(Short value) {
			addCriterion("post_status =", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusNotEqualTo(Short value) {
			addCriterion("post_status <>", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusGreaterThan(Short value) {
			addCriterion("post_status >", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("post_status >=", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusLessThan(Short value) {
			addCriterion("post_status <", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusLessThanOrEqualTo(Short value) {
			addCriterion("post_status <=", value, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusIn(List<Short> values) {
			addCriterion("post_status in", values, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusNotIn(List<Short> values) {
			addCriterion("post_status not in", values, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusBetween(Short value1, Short value2) {
			addCriterion("post_status between", value1, value2, "postStatus");
			return (Criteria) this;
		}

		public Criteria andPostStatusNotBetween(Short value1, Short value2) {
			addCriterion("post_status not between", value1, value2, "postStatus");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Short value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Short value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Short value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Short value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Short value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Short value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Short> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Short> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Short value1, Short value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Short value1, Short value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table klh_product_order
	 * @mbggenerated  Mon Sep 15 23:51:20 CST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table klh_product_order
     *
     * @mbggenerated do_not_delete_during_merge Mon Sep 15 22:59:04 CST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}