package com.bruce.geekway.model;

import java.util.Date;

public class KlhUserScoreLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_user_score_log.id
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_user_score_log.user_open_id
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	private String userOpenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_user_score_log.score_change
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	private Integer scoreChange;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_user_score_log.score_type
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	private Integer scoreType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_user_score_log.reason
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_user_score_log.create_time
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_user_score_log.update_time
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_user_score_log.id
	 * @return  the value of klh_user_score_log.id
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_user_score_log.id
	 * @param id  the value for klh_user_score_log.id
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_user_score_log.user_open_id
	 * @return  the value of klh_user_score_log.user_open_id
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public String getUserOpenId() {
		return userOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_user_score_log.user_open_id
	 * @param userOpenId  the value for klh_user_score_log.user_open_id
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public void setUserOpenId(String userOpenId) {
		this.userOpenId = userOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_user_score_log.score_change
	 * @return  the value of klh_user_score_log.score_change
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public Integer getScoreChange() {
		return scoreChange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_user_score_log.score_change
	 * @param scoreChange  the value for klh_user_score_log.score_change
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public void setScoreChange(Integer scoreChange) {
		this.scoreChange = scoreChange;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_user_score_log.score_type
	 * @return  the value of klh_user_score_log.score_type
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public Integer getScoreType() {
		return scoreType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_user_score_log.score_type
	 * @param scoreType  the value for klh_user_score_log.score_type
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public void setScoreType(Integer scoreType) {
		this.scoreType = scoreType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_user_score_log.reason
	 * @return  the value of klh_user_score_log.reason
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_user_score_log.reason
	 * @param reason  the value for klh_user_score_log.reason
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_user_score_log.create_time
	 * @return  the value of klh_user_score_log.create_time
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_user_score_log.create_time
	 * @param createTime  the value for klh_user_score_log.create_time
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_user_score_log.update_time
	 * @return  the value of klh_user_score_log.update_time
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_user_score_log.update_time
	 * @param updateTime  the value for klh_user_score_log.update_time
	 * @mbggenerated  Wed Oct 29 23:42:01 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	private String userNickname;
	
	public String getUserNickname() {
		return userNickname;
	}

	public void setUserNickname(String userNickname) {
		this.userNickname = userNickname;
	}
}