package com.bruce.geekway.model;

import java.util.Date;

public class KlhUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_user.id
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_user.username
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_user.password
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_user.email
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_user.mobile
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_user.address
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_user.status
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    private Short status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_user.create_time
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_user.update_time
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_user.id
     *
     * @return the value of klh_user.id
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_user.id
     *
     * @param id the value for klh_user.id
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_user.username
     *
     * @return the value of klh_user.username
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_user.username
     *
     * @param username the value for klh_user.username
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_user.password
     *
     * @return the value of klh_user.password
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_user.password
     *
     * @param password the value for klh_user.password
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_user.email
     *
     * @return the value of klh_user.email
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_user.email
     *
     * @param email the value for klh_user.email
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_user.mobile
     *
     * @return the value of klh_user.mobile
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_user.mobile
     *
     * @param mobile the value for klh_user.mobile
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_user.address
     *
     * @return the value of klh_user.address
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_user.address
     *
     * @param address the value for klh_user.address
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_user.status
     *
     * @return the value of klh_user.status
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public Short getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_user.status
     *
     * @param status the value for klh_user.status
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public void setStatus(Short status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_user.create_time
     *
     * @return the value of klh_user.create_time
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_user.create_time
     *
     * @param createTime the value for klh_user.create_time
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_user.update_time
     *
     * @return the value of klh_user.update_time
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_user.update_time
     *
     * @param updateTime the value for klh_user.update_time
     *
     * @mbggenerated Wed May 28 22:22:27 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}