package com.bruce.geekway.model;

import java.util.Date;

public class KlhVoteResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_vote_result.id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_vote_result.vote_id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    private Integer voteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_vote_result.vote_option_id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    private Integer voteOptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_vote_result.vote_user_id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    private Integer voteUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_vote_result.create_time
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column klh_vote_result.update_time
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_vote_result.id
     *
     * @return the value of klh_vote_result.id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_vote_result.id
     *
     * @param id the value for klh_vote_result.id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_vote_result.vote_id
     *
     * @return the value of klh_vote_result.vote_id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public Integer getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_vote_result.vote_id
     *
     * @param voteId the value for klh_vote_result.vote_id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_vote_result.vote_option_id
     *
     * @return the value of klh_vote_result.vote_option_id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public Integer getVoteOptionId() {
        return voteOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_vote_result.vote_option_id
     *
     * @param voteOptionId the value for klh_vote_result.vote_option_id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public void setVoteOptionId(Integer voteOptionId) {
        this.voteOptionId = voteOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_vote_result.vote_user_id
     *
     * @return the value of klh_vote_result.vote_user_id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public Integer getVoteUserId() {
        return voteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_vote_result.vote_user_id
     *
     * @param voteUserId the value for klh_vote_result.vote_user_id
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public void setVoteUserId(Integer voteUserId) {
        this.voteUserId = voteUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_vote_result.create_time
     *
     * @return the value of klh_vote_result.create_time
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_vote_result.create_time
     *
     * @param createTime the value for klh_vote_result.create_time
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column klh_vote_result.update_time
     *
     * @return the value of klh_vote_result.update_time
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column klh_vote_result.update_time
     *
     * @param updateTime the value for klh_vote_result.update_time
     *
     * @mbggenerated Sun Jun 01 09:30:14 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}