package com.bruce.geekway.model;

import java.util.Date;

public class KlhVote {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.id
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.title
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.description
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.vote_mode
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private Short voteMode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.thumb_pic_url
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private String thumbPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.pic_url
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private String picUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.sort
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private Integer sort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.status
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.start_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private Date startTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.end_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.create_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_vote.update_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.id
	 * @return  the value of klh_vote.id
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.id
	 * @param id  the value for klh_vote.id
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.title
	 * @return  the value of klh_vote.title
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.title
	 * @param title  the value for klh_vote.title
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.description
	 * @return  the value of klh_vote.description
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.description
	 * @param description  the value for klh_vote.description
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.vote_mode
	 * @return  the value of klh_vote.vote_mode
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public Short getVoteMode() {
		return voteMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.vote_mode
	 * @param voteMode  the value for klh_vote.vote_mode
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setVoteMode(Short voteMode) {
		this.voteMode = voteMode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.thumb_pic_url
	 * @return  the value of klh_vote.thumb_pic_url
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public String getThumbPicUrl() {
		return thumbPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.thumb_pic_url
	 * @param thumbPicUrl  the value for klh_vote.thumb_pic_url
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setThumbPicUrl(String thumbPicUrl) {
		this.thumbPicUrl = thumbPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.pic_url
	 * @return  the value of klh_vote.pic_url
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.pic_url
	 * @param picUrl  the value for klh_vote.pic_url
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.sort
	 * @return  the value of klh_vote.sort
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public Integer getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.sort
	 * @param sort  the value for klh_vote.sort
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setSort(Integer sort) {
		this.sort = sort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.status
	 * @return  the value of klh_vote.status
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.status
	 * @param status  the value for klh_vote.status
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.start_time
	 * @return  the value of klh_vote.start_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.start_time
	 * @param startTime  the value for klh_vote.start_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.end_time
	 * @return  the value of klh_vote.end_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.end_time
	 * @param endTime  the value for klh_vote.end_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.create_time
	 * @return  the value of klh_vote.create_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.create_time
	 * @param createTime  the value for klh_vote.create_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_vote.update_time
	 * @return  the value of klh_vote.update_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_vote.update_time
	 * @param updateTime  the value for klh_vote.update_time
	 * @mbggenerated  Tue May 27 16:25:00 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}