package com.bruce.geekway.model;

import java.util.Date;

public class KlhWallImageLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image_log.id
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image_log.image_id
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	private Integer imageId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image_log.browse_opt
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	private Short browseOpt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image_log.like_opt
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	private Short likeOpt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image_log.create_time
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image_log.update_time
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image_log.id
	 * @return  the value of klh_wall_image_log.id
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image_log.id
	 * @param id  the value for klh_wall_image_log.id
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image_log.image_id
	 * @return  the value of klh_wall_image_log.image_id
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public Integer getImageId() {
		return imageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image_log.image_id
	 * @param imageId  the value for klh_wall_image_log.image_id
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public void setImageId(Integer imageId) {
		this.imageId = imageId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image_log.browse_opt
	 * @return  the value of klh_wall_image_log.browse_opt
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public Short getBrowseOpt() {
		return browseOpt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image_log.browse_opt
	 * @param browseOpt  the value for klh_wall_image_log.browse_opt
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public void setBrowseOpt(Short browseOpt) {
		this.browseOpt = browseOpt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image_log.like_opt
	 * @return  the value of klh_wall_image_log.like_opt
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public Short getLikeOpt() {
		return likeOpt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image_log.like_opt
	 * @param likeOpt  the value for klh_wall_image_log.like_opt
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public void setLikeOpt(Short likeOpt) {
		this.likeOpt = likeOpt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image_log.create_time
	 * @return  the value of klh_wall_image_log.create_time
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image_log.create_time
	 * @param createTime  the value for klh_wall_image_log.create_time
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image_log.update_time
	 * @return  the value of klh_wall_image_log.update_time
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image_log.update_time
	 * @param updateTime  the value for klh_wall_image_log.update_time
	 * @mbggenerated  Sun Jul 27 10:37:28 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}