package com.bruce.geekway.model;

import java.util.Date;

public class KlhWallImage extends KlhWallImageBase {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image.id
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image.nickname
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image.like_count
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	private Integer likeCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image.thumb_pic_url
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	private String thumbPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image.pic_url
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	private String picUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image.status
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image.create_time
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column klh_wall_image.update_time
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image.id
	 * @return  the value of klh_wall_image.id
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image.id
	 * @param id  the value for klh_wall_image.id
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image.nickname
	 * @return  the value of klh_wall_image.nickname
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image.nickname
	 * @param nickname  the value for klh_wall_image.nickname
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image.like_count
	 * @return  the value of klh_wall_image.like_count
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public Integer getLikeCount() {
		return likeCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image.like_count
	 * @param likeCount  the value for klh_wall_image.like_count
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public void setLikeCount(Integer likeCount) {
		this.likeCount = likeCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image.thumb_pic_url
	 * @return  the value of klh_wall_image.thumb_pic_url
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public String getThumbPicUrl() {
		return thumbPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image.thumb_pic_url
	 * @param thumbPicUrl  the value for klh_wall_image.thumb_pic_url
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public void setThumbPicUrl(String thumbPicUrl) {
		this.thumbPicUrl = thumbPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image.pic_url
	 * @return  the value of klh_wall_image.pic_url
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image.pic_url
	 * @param picUrl  the value for klh_wall_image.pic_url
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image.status
	 * @return  the value of klh_wall_image.status
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image.status
	 * @param status  the value for klh_wall_image.status
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image.create_time
	 * @return  the value of klh_wall_image.create_time
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image.create_time
	 * @param createTime  the value for klh_wall_image.create_time
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column klh_wall_image.update_time
	 * @return  the value of klh_wall_image.update_time
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column klh_wall_image.update_time
	 * @param updateTime  the value for klh_wall_image.update_time
	 * @mbggenerated  Sun Jun 29 22:08:22 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}