package com.bruce.geekway.model;

import java.util.Date;

public class WxDefaultReply {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.id
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.new_subscribe_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private String newSubscribeReply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.re_subscribe_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private String reSubscribeReply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.text_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private String textReply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.image_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private String imageReply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.voice_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private String voiceReply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.menu_click_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private String menuClickReply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.location_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private String locationReply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.video_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private String videoReply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.status
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.create_time
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_default_reply.update_time
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.id
	 * @return  the value of wx_default_reply.id
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.id
	 * @param id  the value for wx_default_reply.id
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.new_subscribe_reply
	 * @return  the value of wx_default_reply.new_subscribe_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public String getNewSubscribeReply() {
		return newSubscribeReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.new_subscribe_reply
	 * @param newSubscribeReply  the value for wx_default_reply.new_subscribe_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setNewSubscribeReply(String newSubscribeReply) {
		this.newSubscribeReply = newSubscribeReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.re_subscribe_reply
	 * @return  the value of wx_default_reply.re_subscribe_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public String getReSubscribeReply() {
		return reSubscribeReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.re_subscribe_reply
	 * @param reSubscribeReply  the value for wx_default_reply.re_subscribe_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setReSubscribeReply(String reSubscribeReply) {
		this.reSubscribeReply = reSubscribeReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.text_reply
	 * @return  the value of wx_default_reply.text_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public String getTextReply() {
		return textReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.text_reply
	 * @param textReply  the value for wx_default_reply.text_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setTextReply(String textReply) {
		this.textReply = textReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.image_reply
	 * @return  the value of wx_default_reply.image_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public String getImageReply() {
		return imageReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.image_reply
	 * @param imageReply  the value for wx_default_reply.image_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setImageReply(String imageReply) {
		this.imageReply = imageReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.voice_reply
	 * @return  the value of wx_default_reply.voice_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public String getVoiceReply() {
		return voiceReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.voice_reply
	 * @param voiceReply  the value for wx_default_reply.voice_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setVoiceReply(String voiceReply) {
		this.voiceReply = voiceReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.menu_click_reply
	 * @return  the value of wx_default_reply.menu_click_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public String getMenuClickReply() {
		return menuClickReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.menu_click_reply
	 * @param menuClickReply  the value for wx_default_reply.menu_click_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setMenuClickReply(String menuClickReply) {
		this.menuClickReply = menuClickReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.location_reply
	 * @return  the value of wx_default_reply.location_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public String getLocationReply() {
		return locationReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.location_reply
	 * @param locationReply  the value for wx_default_reply.location_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setLocationReply(String locationReply) {
		this.locationReply = locationReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.video_reply
	 * @return  the value of wx_default_reply.video_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public String getVideoReply() {
		return videoReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.video_reply
	 * @param videoReply  the value for wx_default_reply.video_reply
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setVideoReply(String videoReply) {
		this.videoReply = videoReply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.status
	 * @return  the value of wx_default_reply.status
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.status
	 * @param status  the value for wx_default_reply.status
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.create_time
	 * @return  the value of wx_default_reply.create_time
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.create_time
	 * @param createTime  the value for wx_default_reply.create_time
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_default_reply.update_time
	 * @return  the value of wx_default_reply.update_time
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_default_reply.update_time
	 * @param updateTime  the value for wx_default_reply.update_time
	 * @mbggenerated  Wed Apr 15 10:33:06 CST 2015
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}