package com.bruce.geekway.model;

import java.util.Date;

public class WxMaterialNews {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_news.id
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_news.title
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_news.link
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	private String link;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_news.cover_image_url
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	private String coverImageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_news.digest
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	private String digest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_news.status
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_news.create_time
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_news.update_time
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_news.id
	 * @return  the value of wx_material_news.id
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_news.id
	 * @param id  the value for wx_material_news.id
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_news.title
	 * @return  the value of wx_material_news.title
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_news.title
	 * @param title  the value for wx_material_news.title
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_news.link
	 * @return  the value of wx_material_news.link
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public String getLink() {
		return link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_news.link
	 * @param link  the value for wx_material_news.link
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public void setLink(String link) {
		this.link = link;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_news.cover_image_url
	 * @return  the value of wx_material_news.cover_image_url
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public String getCoverImageUrl() {
		return coverImageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_news.cover_image_url
	 * @param coverImageUrl  the value for wx_material_news.cover_image_url
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public void setCoverImageUrl(String coverImageUrl) {
		this.coverImageUrl = coverImageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_news.digest
	 * @return  the value of wx_material_news.digest
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public String getDigest() {
		return digest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_news.digest
	 * @param digest  the value for wx_material_news.digest
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public void setDigest(String digest) {
		this.digest = digest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_news.status
	 * @return  the value of wx_material_news.status
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_news.status
	 * @param status  the value for wx_material_news.status
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_news.create_time
	 * @return  the value of wx_material_news.create_time
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_news.create_time
	 * @param createTime  the value for wx_material_news.create_time
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_news.update_time
	 * @return  the value of wx_material_news.update_time
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_news.update_time
	 * @param updateTime  the value for wx_material_news.update_time
	 * @mbggenerated  Mon Aug 11 17:27:10 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}