package com.bruce.geekway.model;

import java.util.Date;

public class WxMaterialArticles {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_articles.id
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_articles.name
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_articles.row_limit
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	private Short rowLimit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_articles.status
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_articles.create_time
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_material_articles.update_time
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_articles.id
	 * @return  the value of wx_material_articles.id
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_articles.id
	 * @param id  the value for wx_material_articles.id
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_articles.name
	 * @return  the value of wx_material_articles.name
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_articles.name
	 * @param name  the value for wx_material_articles.name
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_articles.row_limit
	 * @return  the value of wx_material_articles.row_limit
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public Short getRowLimit() {
		return rowLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_articles.row_limit
	 * @param rowLimit  the value for wx_material_articles.row_limit
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public void setRowLimit(Short rowLimit) {
		this.rowLimit = rowLimit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_articles.status
	 * @return  the value of wx_material_articles.status
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_articles.status
	 * @param status  the value for wx_material_articles.status
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_articles.create_time
	 * @return  the value of wx_material_articles.create_time
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_articles.create_time
	 * @param createTime  the value for wx_material_articles.create_time
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_material_articles.update_time
	 * @return  the value of wx_material_articles.update_time
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_material_articles.update_time
	 * @param updateTime  the value for wx_material_articles.update_time
	 * @mbggenerated  Mon May 12 00:48:09 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}