package com.bruce.geekway.model;

import java.util.Date;

public class WxProductOrderItem {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.product_order_id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private Long productOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.out_trade_no
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private String outTradeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.product_id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.product_sku_id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private Integer productSkuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.product_name
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private String productName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.product_pic_url
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private String productPicUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.item_fee
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private Double itemFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.amount
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private Integer amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.total_fee
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private Double totalFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.status
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.create_time
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order_item.update_time
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.id
	 * @return  the value of wx_product_order_item.id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.id
	 * @param id  the value for wx_product_order_item.id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.product_order_id
	 * @return  the value of wx_product_order_item.product_order_id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public Long getProductOrderId() {
		return productOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.product_order_id
	 * @param productOrderId  the value for wx_product_order_item.product_order_id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setProductOrderId(Long productOrderId) {
		this.productOrderId = productOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.out_trade_no
	 * @return  the value of wx_product_order_item.out_trade_no
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public String getOutTradeNo() {
		return outTradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.out_trade_no
	 * @param outTradeNo  the value for wx_product_order_item.out_trade_no
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.product_id
	 * @return  the value of wx_product_order_item.product_id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.product_id
	 * @param productId  the value for wx_product_order_item.product_id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.product_sku_id
	 * @return  the value of wx_product_order_item.product_sku_id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public Integer getProductSkuId() {
		return productSkuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.product_sku_id
	 * @param productSkuId  the value for wx_product_order_item.product_sku_id
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setProductSkuId(Integer productSkuId) {
		this.productSkuId = productSkuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.product_name
	 * @return  the value of wx_product_order_item.product_name
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.product_name
	 * @param productName  the value for wx_product_order_item.product_name
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.product_pic_url
	 * @return  the value of wx_product_order_item.product_pic_url
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public String getProductPicUrl() {
		return productPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.product_pic_url
	 * @param productPicUrl  the value for wx_product_order_item.product_pic_url
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setProductPicUrl(String productPicUrl) {
		this.productPicUrl = productPicUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.item_fee
	 * @return  the value of wx_product_order_item.item_fee
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public Double getItemFee() {
		return itemFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.item_fee
	 * @param itemFee  the value for wx_product_order_item.item_fee
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setItemFee(Double itemFee) {
		this.itemFee = itemFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.amount
	 * @return  the value of wx_product_order_item.amount
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public Integer getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.amount
	 * @param amount  the value for wx_product_order_item.amount
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setAmount(Integer amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.total_fee
	 * @return  the value of wx_product_order_item.total_fee
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public Double getTotalFee() {
		return totalFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.total_fee
	 * @param totalFee  the value for wx_product_order_item.total_fee
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setTotalFee(Double totalFee) {
		this.totalFee = totalFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.status
	 * @return  the value of wx_product_order_item.status
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.status
	 * @param status  the value for wx_product_order_item.status
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.create_time
	 * @return  the value of wx_product_order_item.create_time
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.create_time
	 * @param createTime  the value for wx_product_order_item.create_time
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order_item.update_time
	 * @return  the value of wx_product_order_item.update_time
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order_item.update_time
	 * @param updateTime  the value for wx_product_order_item.update_time
	 * @mbggenerated  Thu Oct 30 14:29:40 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}