package com.bruce.geekway.model;

import java.util.Date;

public class WxProductSku {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.id
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.product_id
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.out_id
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private String outId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.name
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.description
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.properties_name
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private String propertiesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.num
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private Integer num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.origin_price
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private Long originPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.price
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.sku_pic_url
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private String skuPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.sku_thumb_pic_url
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private String skuThumbPicUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.create_time
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wx_product_sku.update_time
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.id
     *
     * @return the value of wx_product_sku.id
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.id
     *
     * @param id the value for wx_product_sku.id
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.product_id
     *
     * @return the value of wx_product_sku.product_id
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.product_id
     *
     * @param productId the value for wx_product_sku.product_id
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.out_id
     *
     * @return the value of wx_product_sku.out_id
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public String getOutId() {
        return outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.out_id
     *
     * @param outId the value for wx_product_sku.out_id
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setOutId(String outId) {
        this.outId = outId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.name
     *
     * @return the value of wx_product_sku.name
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.name
     *
     * @param name the value for wx_product_sku.name
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.description
     *
     * @return the value of wx_product_sku.description
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.description
     *
     * @param description the value for wx_product_sku.description
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.properties_name
     *
     * @return the value of wx_product_sku.properties_name
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public String getPropertiesName() {
        return propertiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.properties_name
     *
     * @param propertiesName the value for wx_product_sku.properties_name
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setPropertiesName(String propertiesName) {
        this.propertiesName = propertiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.num
     *
     * @return the value of wx_product_sku.num
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.num
     *
     * @param num the value for wx_product_sku.num
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.origin_price
     *
     * @return the value of wx_product_sku.origin_price
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public Long getOriginPrice() {
        return originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.origin_price
     *
     * @param originPrice the value for wx_product_sku.origin_price
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setOriginPrice(Long originPrice) {
        this.originPrice = originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.price
     *
     * @return the value of wx_product_sku.price
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.price
     *
     * @param price the value for wx_product_sku.price
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.sku_pic_url
     *
     * @return the value of wx_product_sku.sku_pic_url
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public String getSkuPicUrl() {
        return skuPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.sku_pic_url
     *
     * @param skuPicUrl the value for wx_product_sku.sku_pic_url
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setSkuPicUrl(String skuPicUrl) {
        this.skuPicUrl = skuPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.sku_thumb_pic_url
     *
     * @return the value of wx_product_sku.sku_thumb_pic_url
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public String getSkuThumbPicUrl() {
        return skuThumbPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.sku_thumb_pic_url
     *
     * @param skuThumbPicUrl the value for wx_product_sku.sku_thumb_pic_url
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setSkuThumbPicUrl(String skuThumbPicUrl) {
        this.skuThumbPicUrl = skuThumbPicUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.create_time
     *
     * @return the value of wx_product_sku.create_time
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.create_time
     *
     * @param createTime the value for wx_product_sku.create_time
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wx_product_sku.update_time
     *
     * @return the value of wx_product_sku.update_time
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wx_product_sku.update_time
     *
     * @param updateTime the value for wx_product_sku.update_time
     *
     * @mbggenerated Tue Sep 16 18:22:03 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}