package com.bruce.geekway.model;

import java.util.Date;

public class WxProductVoucher {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_voucher.id
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_voucher.user_open_id
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	private String userOpenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_voucher.code
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_voucher.price
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	private Double price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_voucher.status
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_voucher.expire_time
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	private Date expireTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_voucher.create_time
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_voucher.update_time
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_voucher.id
	 * @return  the value of wx_product_voucher.id
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_voucher.id
	 * @param id  the value for wx_product_voucher.id
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_voucher.user_open_id
	 * @return  the value of wx_product_voucher.user_open_id
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public String getUserOpenId() {
		return userOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_voucher.user_open_id
	 * @param userOpenId  the value for wx_product_voucher.user_open_id
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public void setUserOpenId(String userOpenId) {
		this.userOpenId = userOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_voucher.code
	 * @return  the value of wx_product_voucher.code
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_voucher.code
	 * @param code  the value for wx_product_voucher.code
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_voucher.price
	 * @return  the value of wx_product_voucher.price
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public Double getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_voucher.price
	 * @param price  the value for wx_product_voucher.price
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public void setPrice(Double price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_voucher.status
	 * @return  the value of wx_product_voucher.status
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_voucher.status
	 * @param status  the value for wx_product_voucher.status
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_voucher.expire_time
	 * @return  the value of wx_product_voucher.expire_time
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public Date getExpireTime() {
		return expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_voucher.expire_time
	 * @param expireTime  the value for wx_product_voucher.expire_time
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_voucher.create_time
	 * @return  the value of wx_product_voucher.create_time
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_voucher.create_time
	 * @param createTime  the value for wx_product_voucher.create_time
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_voucher.update_time
	 * @return  the value of wx_product_voucher.update_time
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_voucher.update_time
	 * @param updateTime  the value for wx_product_voucher.update_time
	 * @mbggenerated  Tue Sep 23 15:32:54 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}