package com.bruce.geekway.model;

import java.util.Date;

public class WxProductOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.user_open_id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String userOpenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.out_trade_no
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String outTradeNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.wx_trans_id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String wxTransId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.title
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.product_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private Double productFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.transport_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private Double transportFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.discount_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private Double discountFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.voucher_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private Double voucherFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.total_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private Double totalFee;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.voucher_id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private Long voucherId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.post_type
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String postType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.post_sn
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String postSn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.post_name
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String postName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.post_mobile
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String postMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.post_province
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String postProvince;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.post_city
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String postCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.post_countries
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String postCountries;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.post_address_detail_info
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String postAddressDetailInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.post_code
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.post_national_code
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private String postNationalCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.status
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.create_time
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_product_order.update_time
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.id
	 * @return  the value of wx_product_order.id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.id
	 * @param id  the value for wx_product_order.id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.user_open_id
	 * @return  the value of wx_product_order.user_open_id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getUserOpenId() {
		return userOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.user_open_id
	 * @param userOpenId  the value for wx_product_order.user_open_id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setUserOpenId(String userOpenId) {
		this.userOpenId = userOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.out_trade_no
	 * @return  the value of wx_product_order.out_trade_no
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getOutTradeNo() {
		return outTradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.out_trade_no
	 * @param outTradeNo  the value for wx_product_order.out_trade_no
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.wx_trans_id
	 * @return  the value of wx_product_order.wx_trans_id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getWxTransId() {
		return wxTransId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.wx_trans_id
	 * @param wxTransId  the value for wx_product_order.wx_trans_id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setWxTransId(String wxTransId) {
		this.wxTransId = wxTransId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.title
	 * @return  the value of wx_product_order.title
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.title
	 * @param title  the value for wx_product_order.title
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.product_fee
	 * @return  the value of wx_product_order.product_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public Double getProductFee() {
		return productFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.product_fee
	 * @param productFee  the value for wx_product_order.product_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setProductFee(Double productFee) {
		this.productFee = productFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.transport_fee
	 * @return  the value of wx_product_order.transport_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public Double getTransportFee() {
		return transportFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.transport_fee
	 * @param transportFee  the value for wx_product_order.transport_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setTransportFee(Double transportFee) {
		this.transportFee = transportFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.discount_fee
	 * @return  the value of wx_product_order.discount_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public Double getDiscountFee() {
		return discountFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.discount_fee
	 * @param discountFee  the value for wx_product_order.discount_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setDiscountFee(Double discountFee) {
		this.discountFee = discountFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.voucher_fee
	 * @return  the value of wx_product_order.voucher_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public Double getVoucherFee() {
		return voucherFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.voucher_fee
	 * @param voucherFee  the value for wx_product_order.voucher_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setVoucherFee(Double voucherFee) {
		this.voucherFee = voucherFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.total_fee
	 * @return  the value of wx_product_order.total_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public Double getTotalFee() {
		return totalFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.total_fee
	 * @param totalFee  the value for wx_product_order.total_fee
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setTotalFee(Double totalFee) {
		this.totalFee = totalFee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.voucher_id
	 * @return  the value of wx_product_order.voucher_id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public Long getVoucherId() {
		return voucherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.voucher_id
	 * @param voucherId  the value for wx_product_order.voucher_id
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setVoucherId(Long voucherId) {
		this.voucherId = voucherId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.post_type
	 * @return  the value of wx_product_order.post_type
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getPostType() {
		return postType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.post_type
	 * @param postType  the value for wx_product_order.post_type
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setPostType(String postType) {
		this.postType = postType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.post_sn
	 * @return  the value of wx_product_order.post_sn
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getPostSn() {
		return postSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.post_sn
	 * @param postSn  the value for wx_product_order.post_sn
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setPostSn(String postSn) {
		this.postSn = postSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.post_name
	 * @return  the value of wx_product_order.post_name
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getPostName() {
		return postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.post_name
	 * @param postName  the value for wx_product_order.post_name
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setPostName(String postName) {
		this.postName = postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.post_mobile
	 * @return  the value of wx_product_order.post_mobile
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getPostMobile() {
		return postMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.post_mobile
	 * @param postMobile  the value for wx_product_order.post_mobile
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setPostMobile(String postMobile) {
		this.postMobile = postMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.post_province
	 * @return  the value of wx_product_order.post_province
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getPostProvince() {
		return postProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.post_province
	 * @param postProvince  the value for wx_product_order.post_province
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setPostProvince(String postProvince) {
		this.postProvince = postProvince;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.post_city
	 * @return  the value of wx_product_order.post_city
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getPostCity() {
		return postCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.post_city
	 * @param postCity  the value for wx_product_order.post_city
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setPostCity(String postCity) {
		this.postCity = postCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.post_countries
	 * @return  the value of wx_product_order.post_countries
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getPostCountries() {
		return postCountries;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.post_countries
	 * @param postCountries  the value for wx_product_order.post_countries
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setPostCountries(String postCountries) {
		this.postCountries = postCountries;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.post_address_detail_info
	 * @return  the value of wx_product_order.post_address_detail_info
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getPostAddressDetailInfo() {
		return postAddressDetailInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.post_address_detail_info
	 * @param postAddressDetailInfo  the value for wx_product_order.post_address_detail_info
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setPostAddressDetailInfo(String postAddressDetailInfo) {
		this.postAddressDetailInfo = postAddressDetailInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.post_code
	 * @return  the value of wx_product_order.post_code
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.post_code
	 * @param postCode  the value for wx_product_order.post_code
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.post_national_code
	 * @return  the value of wx_product_order.post_national_code
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public String getPostNationalCode() {
		return postNationalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.post_national_code
	 * @param postNationalCode  the value for wx_product_order.post_national_code
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setPostNationalCode(String postNationalCode) {
		this.postNationalCode = postNationalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.status
	 * @return  the value of wx_product_order.status
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.status
	 * @param status  the value for wx_product_order.status
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.create_time
	 * @return  the value of wx_product_order.create_time
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.create_time
	 * @param createTime  the value for wx_product_order.create_time
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_product_order.update_time
	 * @return  the value of wx_product_order.update_time
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_product_order.update_time
	 * @param updateTime  the value for wx_product_order.update_time
	 * @mbggenerated  Sun Nov 09 18:59:40 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}