package com.bruce.geekway.model;

import java.util.Date;

public class WxSkuProp {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_sku_prop.id
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_sku_prop.category_id
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	private Integer categoryId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_sku_prop.name
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_sku_prop.description
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_sku_prop.create_time
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_sku_prop.update_time
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_sku_prop.id
	 * @return  the value of wx_sku_prop.id
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_sku_prop.id
	 * @param id  the value for wx_sku_prop.id
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_sku_prop.category_id
	 * @return  the value of wx_sku_prop.category_id
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public Integer getCategoryId() {
		return categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_sku_prop.category_id
	 * @param categoryId  the value for wx_sku_prop.category_id
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_sku_prop.name
	 * @return  the value of wx_sku_prop.name
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_sku_prop.name
	 * @param name  the value for wx_sku_prop.name
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_sku_prop.description
	 * @return  the value of wx_sku_prop.description
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_sku_prop.description
	 * @param description  the value for wx_sku_prop.description
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_sku_prop.create_time
	 * @return  the value of wx_sku_prop.create_time
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_sku_prop.create_time
	 * @param createTime  the value for wx_sku_prop.create_time
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_sku_prop.update_time
	 * @return  the value of wx_sku_prop.update_time
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_sku_prop.update_time
	 * @param updateTime  the value for wx_sku_prop.update_time
	 * @mbggenerated  Wed Sep 17 09:41:59 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}