package com.bruce.geekway.model;

import java.util.Date;

public class WxUserAddress {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.id
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.user_open_id
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private String userOpenId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.post_name
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private String postName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.post_mobile
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private String postMobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.post_address
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private String postAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.post_code
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.province
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.city
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.country
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.address_detail
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private String addressDetail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.national_code
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private String nationalCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.status
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.create_time
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_user_address.update_time
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.id
	 * @return  the value of wx_user_address.id
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.id
	 * @param id  the value for wx_user_address.id
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.user_open_id
	 * @return  the value of wx_user_address.user_open_id
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public String getUserOpenId() {
		return userOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.user_open_id
	 * @param userOpenId  the value for wx_user_address.user_open_id
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setUserOpenId(String userOpenId) {
		this.userOpenId = userOpenId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.post_name
	 * @return  the value of wx_user_address.post_name
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public String getPostName() {
		return postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.post_name
	 * @param postName  the value for wx_user_address.post_name
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setPostName(String postName) {
		this.postName = postName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.post_mobile
	 * @return  the value of wx_user_address.post_mobile
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public String getPostMobile() {
		return postMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.post_mobile
	 * @param postMobile  the value for wx_user_address.post_mobile
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setPostMobile(String postMobile) {
		this.postMobile = postMobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.post_address
	 * @return  the value of wx_user_address.post_address
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public String getPostAddress() {
		return postAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.post_address
	 * @param postAddress  the value for wx_user_address.post_address
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setPostAddress(String postAddress) {
		this.postAddress = postAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.post_code
	 * @return  the value of wx_user_address.post_code
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.post_code
	 * @param postCode  the value for wx_user_address.post_code
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.province
	 * @return  the value of wx_user_address.province
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.province
	 * @param province  the value for wx_user_address.province
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.city
	 * @return  the value of wx_user_address.city
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.city
	 * @param city  the value for wx_user_address.city
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.country
	 * @return  the value of wx_user_address.country
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.country
	 * @param country  the value for wx_user_address.country
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.address_detail
	 * @return  the value of wx_user_address.address_detail
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public String getAddressDetail() {
		return addressDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.address_detail
	 * @param addressDetail  the value for wx_user_address.address_detail
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setAddressDetail(String addressDetail) {
		this.addressDetail = addressDetail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.national_code
	 * @return  the value of wx_user_address.national_code
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public String getNationalCode() {
		return nationalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.national_code
	 * @param nationalCode  the value for wx_user_address.national_code
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setNationalCode(String nationalCode) {
		this.nationalCode = nationalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.status
	 * @return  the value of wx_user_address.status
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.status
	 * @param status  the value for wx_user_address.status
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.create_time
	 * @return  the value of wx_user_address.create_time
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.create_time
	 * @param createTime  the value for wx_user_address.create_time
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_user_address.update_time
	 * @return  the value of wx_user_address.update_time
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_user_address.update_time
	 * @param updateTime  the value for wx_user_address.update_time
	 * @mbggenerated  Sat Sep 27 08:51:21 CST 2014
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}