package com.bruce.geekway.model;

import java.util.Date;

public class WxWebUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.id
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.user_type
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private Short userType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.open_id
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private String openId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.union_id
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private String unionId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.nickname
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.sex
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private Short sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.city
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.province
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.country
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private String country;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.language
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private String language;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.head_img_url
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private String headImgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.subscribe_status
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private Short subscribeStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.status
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.create_time
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column wx_web_user.update_time
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.id
	 * @return  the value of wx_web_user.id
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.id
	 * @param id  the value for wx_web_user.id
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.user_type
	 * @return  the value of wx_web_user.user_type
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public Short getUserType() {
		return userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.user_type
	 * @param userType  the value for wx_web_user.user_type
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setUserType(Short userType) {
		this.userType = userType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.open_id
	 * @return  the value of wx_web_user.open_id
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public String getOpenId() {
		return openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.open_id
	 * @param openId  the value for wx_web_user.open_id
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setOpenId(String openId) {
		this.openId = openId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.union_id
	 * @return  the value of wx_web_user.union_id
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public String getUnionId() {
		return unionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.union_id
	 * @param unionId  the value for wx_web_user.union_id
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setUnionId(String unionId) {
		this.unionId = unionId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.nickname
	 * @return  the value of wx_web_user.nickname
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.nickname
	 * @param nickname  the value for wx_web_user.nickname
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.sex
	 * @return  the value of wx_web_user.sex
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public Short getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.sex
	 * @param sex  the value for wx_web_user.sex
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setSex(Short sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.city
	 * @return  the value of wx_web_user.city
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.city
	 * @param city  the value for wx_web_user.city
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.province
	 * @return  the value of wx_web_user.province
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.province
	 * @param province  the value for wx_web_user.province
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.country
	 * @return  the value of wx_web_user.country
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.country
	 * @param country  the value for wx_web_user.country
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.language
	 * @return  the value of wx_web_user.language
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.language
	 * @param language  the value for wx_web_user.language
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setLanguage(String language) {
		this.language = language;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.head_img_url
	 * @return  the value of wx_web_user.head_img_url
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public String getHeadImgUrl() {
		return headImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.head_img_url
	 * @param headImgUrl  the value for wx_web_user.head_img_url
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setHeadImgUrl(String headImgUrl) {
		this.headImgUrl = headImgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.subscribe_status
	 * @return  the value of wx_web_user.subscribe_status
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public Short getSubscribeStatus() {
		return subscribeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.subscribe_status
	 * @param subscribeStatus  the value for wx_web_user.subscribe_status
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setSubscribeStatus(Short subscribeStatus) {
		this.subscribeStatus = subscribeStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.status
	 * @return  the value of wx_web_user.status
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.status
	 * @param status  the value for wx_web_user.status
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.create_time
	 * @return  the value of wx_web_user.create_time
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.create_time
	 * @param createTime  the value for wx_web_user.create_time
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column wx_web_user.update_time
	 * @return  the value of wx_web_user.update_time
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column wx_web_user.update_time
	 * @param updateTime  the value for wx_web_user.update_time
	 * @mbggenerated  Fri Jan 16 17:58:43 CST 2015
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}